# Generated by Django 2.0.3 on 2018-03-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messaggio',
        ),
    ]
